### PR TITLE
85 bug make legend not cover charts

### PR DESCRIPTION
**Pull request by NilsArnlund**
Fixed the problem with the navbar covering graphs. It is now also scroleble when there is alot of ledgends.

This does note look good when no sites/ledgends are in and the navbar is in "open mode" 
But when filled it looks nice. There will be a new task next week before DEMO for Sectra where this is solved. 
An issue where the website looks good even when no visualisation is uploaded/in and a general fix of the styling. 
Solving this problem probably includes make the navbar in "open mode" be certain with instead of flex.
Yes, we could have worked more on this here however if not done all the way that would just have been extra work for no reason.

### CODE REVIEW

**Comment by ViktorAndersson99** [comment]
Tested in chrome. Legend bar is not centered, even when multiple sites is used. 

image

**Comment by ViktorAndersson99** [comment]
Not sure if this will be fixed in another task. But i think we should make sure that the navbar is not changing the width of the website, and that its placed at the top and in the top left corner.

image

**Comment by NilsArnlund** [comment]
> 

Why should it not be? The not yet done task should build on this "solution". If not merged this issue is completely useless

**Comment by ViktorAndersson99** [comment]
> Why should it not be? The not yet done task should build on this "solution". If not merged this issue is completely useless

Since if the new task is not completed in time the current version of main is in my opinion preferred to use for the sectra demo and final presentation. The next task can still depend on this issue without any problem. Just merge with this branch. Just my opinion we can still merge this with main if you think its important

**Comment by NilsArnlund** [comment]
> Since if the new task is not completed in time the current version of main is in my opinion preferred to use for the sectra demo and final presentation. The next task can still depend on this issue without any problem. Just merge with this branch. But sure we can still merge this with main if you think its important

That is very true, you are correct, forgot that you could merge with this bransch without it being in main ... 
My hope is that the not yet done task can be done by then, but if not, we will use the navbar currently found in main.

**Comment by AlgotE** [comment]
I have pushed styling fixes for legendbar and graphs

**Review by Dethcrvsh — COMMENTED** [review]
I think it looks ok. However, the page is not scrollable anymore, at least not in Firefox. I checked with main, and it seems to work there.

**Review by Dethcrvsh — APPROVED** [review]
Looks good!

**Pull request merged**
