### PR TITLE
81 feature style and fix the frontend

### PR DESCRIPTION
**Pull request by ELEMENTLHERO**

### CODE REVIEW

**Review by NilsArnlund — DISMISSED** [review]
It looks better. Haven't really tested every thing in and out but it looks like nothing else is broken. Would be good to get this in before Demo I think. Some more colours in the menu and the info-boxes need some love in the future.

**Review by AlgotE — CHANGES_REQUESTED** [review]
There are too many bugs in this to merge it with main.

The menu covers the graphs if not in fullscreen:
bild

The graphs get smaller if you close the menu:
bild
bild

The legend gets cut off if there are many files uploaded:
bild

The info-boxes looks a really nice though, maybe create a new branch with just this feature and a separate PR for that style fix. 
Suggestion: center the info-boxes to the container/box, probably with Align-items
bild

**Comment by AlgotE** [comment]
The legend bug seems to be present in main as well, so please ignore that one. I will create a seperate bug report for it, the other bugs can not be reproduced in main

**Comment by ELEMENTLHERO** [comment]
@AlgotE 

> The menu covers the graphs if not in full-screen:

Fixed, but only for 100-50% not for smaller than 50% (works exactly for 50% not one pixel less)
> The graphs get smaller if you close the menu:

Fixed
> The legend gets cut off if there are many files uploaded:

Not fixed
> The info-boxes looks a really nice though, maybe create a new branch with just this feature and a separate PR for that style fix.
> Suggestion: center the info-boxes to the container/box, probably with Align-items

Made info boxes a bit better, looks a bit weird with 50% + menu right now

Fixed the following issues:
@ELEMENTLHERO
[Auto size Info boxes, fixed menu causing smaller graph, works in half screen (exactly) with menu open](https://github.com/PUM04/pum-04/pull/119/commits/08d5e50fe5540182137450c20cd8f79ed5f689af)

**Review by AlgotE — APPROVED** [review]
Looks a lot better, good job. I think this can be merged to main for the upcoming demo

**Review by AlgotE — APPROVED** [review]
Check changes to main and make sure this is merged with main,

**Review by Dethcrvsh — APPROVED** [review]
Everything seems to be working. Looks good to me!

**Pull request merged**
