### PR TITLE
Fixed the info box bug

### PR DESCRIPTION
**Pull request by Dethcrvsh**

### CODE REVIEW

**Review by ELEMENTLHERO — APPROVED** [review]
Looks good!

**Comment by Dethcrvsh** [comment]
Are you sure you have recompiled the C++ code? It seems to be working for me.
image

**Comment by AlgotE** [comment]
> > Does not seem to have had the desired effect. I still get the wrong min and max for bbvmvh. bild I can not identify the error, the code looks alright
> 
> Are you sure you have recompiled the C++ code? It seems to be working for me. image

This seems to have solved the issue 😅

**Review by AlgotE — APPROVED** [review]
Info-boxes now show the correct max-min

**Pull request merged**
